### ISSUE TITLE
Introduce TypeScript version

### ISSUE THREAD

**Issue by pawsong** [andyhall/voxel-physics-engine#1]
Hi @andyhall. Thank you for sharing this simple and great engine!

I post this issue to introduce typescript version of this library [pawsong/voxel-physics-engine](https://github.com/pawsong/voxel-physics-engine). I prefer using typescript to take advantage of auto complete and build time type checking, which is great for refactoring a large codebase.

I didn't make a PR as javascript has its own advantages :) Thanks again!

**Comment by fenomas** [comment]
Hey, thanks for doing this! I'm keeping my project in JS right now but TS seems really promising and it's great to have options. When I get a chance I'll add a link from the project readme!

Also if you add any significant features please ping me - maybe I can backport, or otherwise keep the two modules in sync. I don't have anything particular planned on my side.

BTW, you might want to make your library a standalone repo, instead of a fork. I believe forks don't show up in github searches, so it will be hard for people to find otherwise.

**Comment by pawsong** [comment]
I'm glad you like it :) I can make a PR for new features!

By the way, I been building my own voxel engine as a fork of [voxel/voxel-engine-stackgl](https://github.com/voxel/voxel-engine-stackgl), and found your [noa](https://github.com/andyhall/noa) engine yesterday. noa is pretty simple and neat! I considered using noa and decided to stay with my voxel-engine-stackgl fork because of these reasons:
- Babylon dependency
  - I don't know babylon very well :) Just don't want to add a massive dependency.
- Javascript
  - As I prefer using typescript. Writing typings for noa is a viable option, but this option cannot take advantage of power of typescript while developing engine itself.

I will keep thinking about contributing to your great works :) Have a nice day and please let me know if you need any help.
