### ISSUE TITLE
How does this optimize for sleeping objects?

### ISSUE THREAD

**Issue by terrac** [andyhall/voxel-physics-engine#2]
I'm running into some performance issues using this and the noa engine and I was wondering how sleeping objects are handled.

Does this have the logic of "after x milliseconds with no collisions put to sleep"?  Which as I understand basically means that collisions for it are checked more infrequently to optimize for active objects.  I'm not an expert so I could be wrong.

Thanks

**Comment by fenomas** [comment]
Hi, nothing like that up to now, but I just pushed a minimal fix that seems to work okay. Can you try it out and see if it helps?

**Comment by terrac** [comment]
Works well overall.

I'm thinking of adding a setVelocity function to rigid body that marks the object active.  Do you see any issues with that?

**Comment by fenomas** [comment]
Hi, I just pushed a fix to this - now a sleeping body can wake up due to gravity (e.g. because it was sitting on a solid voxel and the voxel got removed).

If you want to change the body's velocity directly, you can use the `velocity` array, and then call the newly added `_markActive()` to mark the body as awake:

```js
function setBodyVelocity(body, vel) {
    for (var i=0; i<3; i++) body.velocity[i] = vel[i]
    body._markActive()
}
```

Note that directly changing the velocity is a bit unphysical though, you may get a more physical feel from using `body.applyForce()` and `body.applyImpulse()`. No need to mark the body as active when using the regular APIs.

**Comment by terrac** [comment]
That makes sense.  I was setting the velocity for a dash attack, but it seems like according to https://gamedev.stackexchange.com/questions/34069/what-is-the-difference-between-an-impulse-and-a-force-related-to-a-physics-engine applying an impulse would be good if I was adding forces to it as well.

**Comment by fenomas** [comment]
There are basically three things to consider:

 1. Whether the movement is gradual or instant
 2. Whether the movement should wipe out existing momentum
 3. Whether the movement should affect heavy and light things the same way

Forces are gradual, impulses are instant, and both will move a light body more than a heavy one, whereas changing the velocity of course doesn't depend on mass. 

But re 2:, consider if the character dashes sideways while falling, should the dash wipe out their downward velocity? If so, zero out the velocity vector before applying the movement; if not you need to add to the current velocity, not overwrite it.
