### ISSUE TITLE
Update example

### ISSUE THREAD

**Issue by lino-levan** [andyhall/voxel-physics-engine#6]
The example is out of date. It also looks like the typescript definition is out of date as well?

**Comment by fenomas** [comment]
I see the readme was out of date in several places - I just pushed an update, thanks!

What's wrong with the typescript defs?

**Comment by lino-levan** [comment]
I will try replacing my current physics engine (rapier-js) with this when I get the chance to get you some more detailed feedback. I'll probably just make a PR fixing type definitions if I notice anything is wrong or incomplete (there are a lot of any types).

I would really appreciate some examples of the following in the readme:
```javascript
const aabb = "???" // what is this? It looks like it's an object from your aabb library but it's not re-exported here so it's really awkward to set
const mass = 10 // is it just some number? are there units? are decimals allowed?
const friction = 0.5 // can it be greater than 1?
const restitution = 0.5 // can it be greater than 1?
const gravityMult = 1 // what does this even mean?
const onCollide = ()=>{
    console.log("collided!")
} // are there any inputs? 

var body = phys.addBody( aabb, mass, friction, restitution, gravityMult, onCollide )
```

I haven't tested the Physics constructor so I don't have any issues with that right now, especially since you gave examples of inputs in the readme. 

This library looks perfect for [a project I'm building](https://github.com/lino-levan/afterthought), and in comparison to the other libraries I've seen online it's significantly better (the api looks nicer, the performance looks acceptable, and it looks like it's being maintained(?)). My one complaint is that I tried rewriting my physics back in v0.0.3 to use this engine and it just wouldn't work for me, given the out of date docs and what I believe to be broken type defs.

If you could add some example values, or really docs of any kind on them, that would be amazing. Love the work! Cheers!

**Comment by fenomas** [comment]
Hi! Yes, this was mostly written quite a while ago, and most properties/methods don't have type decorations. But the library is maintained and bug-free as far as I know, and should be fast. But be warned that it's performant because it's a toy engine - it assumes all rigid bodies are AABBs, and it only collides bodies with terrain, not with each other. But if those limitations work for you, this engine will probably be faster than most alternatives thanks to its simplicity.

Answers to questions:

 * `aabb` means an [aabb-3d](https://www.npmjs.com/package/aabb-3d) instance
 * physical properties are all standard definitions/units - friction and restitution are standard coefficients, etc. Units are unspecified, except that distances are in voxel widths
 * `gravityMult` is what it says, a multiplier for gravity for that body (to make objects more floaty, etc)
 * `onCollide` passes a vec3 of the collision impulse values along each axis - I added this to the readme

I can try to add type decorations someday, but for now hope this helps..
